import React from 'react';

export default function PrintDocket({ pipeline }) {
  if (!pipeline) return null;

  return (
    <div id="print-docket" className="hidden p-8 text-black bg-white">
      <h1 className="text-2xl font-bold border-b-2 border-black pb-2">
        CIVIC COMPLIANCE DOCKET &amp; WARD AUDIT
      </h1>
      <p className="text-xs mt-1 text-gray-700">
        Generated by CivicRoute Municipal Dependency Visualizer (PSWB02) — {pipeline.title} ({pipeline.id})
      </p>

      <div className="mt-4 border p-3 rounded text-xs bg-gray-50">
        <p><strong>Jurisdiction:</strong> {pipeline.jurisdiction}</p>
        <p><strong>Primary Desk:</strong> {pipeline.primaryDept}</p>
        <p><strong>Estimated SLA:</strong> {pipeline.cycleTime}</p>
        <p><strong>Statutory Fees:</strong> {pipeline.totalFee}</p>
      </div>

      <div className="mt-6 space-y-3">
        <h2 className="text-sm font-bold uppercase tracking-wider">Required Compliance Milestones</h2>
        {pipeline.nodes.map((node, i) => (
          <div key={node.id} className="border border-gray-300 p-3 rounded text-xs">
            <div className="font-bold text-sm">
              Step {i + 1}: {node.title} ({node.code})
            </div>
            <div className="mt-1 text-gray-700">
              Department: {node.dept} | Fee: {node.fee} | SLA: {node.time} | Mode: {node.type}
            </div>
            <div className="mt-1 text-gray-700">
              <strong>Verified Portal:</strong> {node.url}
            </div>
            <div className="mt-1 text-gray-700">
              <strong>Required Proofs:</strong> {(node.docs || []).join(', ')}
            </div>
            <div className="mt-1 text-gray-700">
              <strong>Status:</strong> {node.status.toUpperCase()}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
